version: '3'

services:
  web:
    command: yarn start
    ports:
      - "3000:3000"
    expose:
      - 3000
    build:
      context: web/.
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_BASE_URL: http://localhost:4000
    env_file:
      - web/.env
    depends_on:
      - api

  api:
    command: /main
    ports:
      - "4000:4000"
    expose:
      - 4000
    build:
      context: server/.
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: postgres://postgres:${DB_PASSWORD}@db:5432/suvanosa
    env_file:
      - server/.env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: suvanosa
    volumes:
      - suvanosa_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  suvanosa_data: